version: '3.9'

services:
  server:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app  
      - /app/node_modules  
    environment:
      DATABASE_HOST: mongodb  
      DATABASE_PORT: 27017
      DATABASE_USER: admin
      DATABASE_PASSWORD: 123
    depends_on:
      - mongodb
  mongodb:
    image: 'mongo:6'
    container_name: mongodb  
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
